[storage]
vault_dir = ./data/vault
library_dir = ./data
database_dir = ./data/
art_cache = ./data/cache/art
overrides_file = ./data/overrides.json
cache_dir = ./data/cache/player
vault_format = {artist}/{album} ({year})/{track_num:02d} - {track_title}

[cd]
cd_device_uri = cdda:///dev/sr0
cd_open_timeout = 10
cd_speed = 16

[musicbrainz]
agent = HiFiBerryMusicPlayer
version = 3.0
mail = none

[ffmpeg]
#options = -codec:a libmp3lame -b:a 320k -ar 44100 -ac 2
#format = mp3
options = -codec:a flac -compression_level 8 -sample_fmt s16 -ar 44100
format = flac